<a href="https://colab.research.google.com/github/Shushilasingh/python-series-for-beginers/blob/main/arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#arrays in python

In [ ]:
import array
a = array.array('i',[4,6,2,9])
#arr = array('d',[1.5,-2.2,3,5.75])
print('the array elements are:')
for elements in a:
  print(elements)



the array elements are:
4
6
2
9


In [ ]:
from array import *
x=array('i',[10,20,30,40,50])
n = len(x)
for i in  range(n):
  print(x[i], end=' ')


10 20 30 40 50 

sorting the array of elemnets using buuble sort technique

In [ ]:
from array import*
x= array('i',[])
print('how many elements? ',end=' ')
n = int(input())

for i in range(n):
  print('enter element: ',end='')
  x.append(int(input()))
print('original array: ', x)


how many elements?  

In [ ]:
marks = array([[50,60,66,72],[60,89,90,66],[20,23,54,55]])

multi dimentional array

In [ ]:
#creating Arrays using logspace
from numpy import*
a= logspace(1,4,5)
n = len(a)
for i in range(n):
  print('%.if' % a[i], end=' ')

In [ ]:
#creating arrays using arange function()
from numpy import *
a = array([1,2,3,4,5])
b = array(a)
c = a
print("a = ",a)
print("b = ",b)
print("c = ",c)

a =  [1 2 3 4 5]
b =  [1 2 3 4 5]
c =  [1 2 3 4 5]


In [ ]:
# creating array usin linspace
from numpy import linspace
a = linspace(0, 11, 3)
print('a = ',a)

a =  [ 0.   5.5 11. ]


In [ ]:
#creating array using arrange function
from numpy import *
a = arange(2,11,2)
print(a)

[ 2  4  6  8 10]


In [ ]:
#creating arrays using zeroes() and ones() functions
from numpy import *
a = zeros(5, int)
print(a)
b = ones(5)
print(b)

[0 0 0 0 0]
[1. 1. 1. 1. 1.]


In [ ]:
#mathematical operations on arrays
arr = array([10, 20, 30, 40])
arr = arr +5
arr1 = array([10, 20, 30, 40])
arr2 = array([1,2,3,4])
arr3 = arr1 -arr2
print(arr3)

[ 9 18 27 36]


In [ ]:
#mathematical operation
from numpy import *
arr = array([10, 20, 30.5,-40])
print("original array: ", arr)
print("After addng 5: ",arr+5)
print("After subtracing 5: ", arr-5)
print("After multiplying with 5: ", arr*5)
print("After dividing with 5: ", arr/5)
print("After modulus with 5: ", arr%5)
print("Expression value: ", (arr+5)**2-10)

original array:  [ 10.   20.   30.5 -40. ]
After addng 5:  [ 15.   25.   35.5 -35. ]
After subtracing 5:  [  5.   15.   25.5 -45. ]
After multiplying with 5:  [  50.   100.   152.5 -200. ]
After dividing with 5:  [ 2.   4.   6.1 -8. ]
After modulus with 5:  [0.  0.  0.5 0. ]
Expression value:  [ 215.    615.   1250.25 1215.  ]


In [ ]:
#comparing array
#to know  the result of comparing two arrays
from numpy import *
a = array([1,2,3,0])
b = array([0,2,3,1])
c = a == b
print('Result of a==b: ', c)
c = a>b
print('Result of a>b: ', c)
c = a <= b
print('Result of a<=b: ',c)

Result of a==b:  [False  True  True False]
Result of a>b:  [ True False False False]
Result of a<=b:  [False  True  True  True]


In [ ]:
#for boolean arrays
#logical_and(), logical_or, logical_not for boolean expressions
from numpy import *
a = array([1,2,3] , int)
b =array([0,2,3] , int)
c = logical_and(a>0, a<4)
print(c)
c =  logical_or(b>=0, b==1)
print(c)
c = logical_not(b)
print(c)


[ True  True  True]
[ True  True  True]
[ True False False]


In [ ]:
#Aliasing the Arrays
from numpy import *
a = arange(1,6)
b = a
print('Original array: ',a)
print('Alias array: ',b)
b[0]=99
print('After modification: ')
print('original array: ', a)
print('Alias array: ',b)

Original array:  [1 2 3 4 5]
Alias array:  [1 2 3 4 5]
After modification: 
original array:  [99  2  3  4  5]
Alias array:  [99  2  3  4  5]


In [ ]:
#viewing and copying array
from numpy import *
a = arange(1,6)
b = a.view()
print('original array: ', b)
print('New array: ', b)


original array:  [1 2 3 4 5]
New array:  [1 2 3 4 5]


In [ ]:
#slicing and indexing of an arrya
from numpy import *
#create array a with elements 10 to 15
a = arange(10, 16)
print(a)
#retrieving  from 1st  to one  element prior to 6th element in steps of 2
b = a[1:6:2]
print(b)
#retrieving  from 6-2= 4th to one element prior to 2nd element in #decreasing stepmsixe
b = a[-2:2:-1]
print(b)
#retrieving from 0th to one elemnt prior to 4th elemnt (6-2= 4th)
b = a[:-2:]
print(b)

[10 11 12 13 14 15]
[11 13 15]
[14 13]
[10 11 12 13]


In [ ]:
#indexing an array
from numpy import *
#create array a with elements 10 to 15
a = arange(10,16)
print(a)
#retrieving  from 1st to one element prior to 6th element i steps of 2
a = a[1:6:2]
print(a)
# display elements using indexing
i=0
while(i<len(a)):
  print(a[i])
  i+=1

[10 11 12 13 14 15]
[11 13 15]
11
13
15


In [ ]:
#diensions of array
arr1 = array([1,2,3,3,4,5])
print(arr1)
arr2 = array([10,
              20,
              30,
              40])
print(arr2)

[1 2 3 3 4 5]
[10 20 30 40]
